import Head from "next/head";
import NewReleases from "../components/layout/NewReleases";
import { getMovies } from "../helpers/api-util";
// import { getNewReleases } from "../helpers/api-util";

export default function Home({ newReleases, popularMovies, topRatedMovies }) {
  console.log(newReleases, popularMovies, topRatedMovies);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NewReleases />
    </>
  );
}

export async function getStaticProps() {
  // let newReleasesUrl = `https://api.themoviedb.org/3/movie/now_playing?api_key=${process.env.API_KEY}&language=en-GB&page=1&region=GB`;
  // let popularMoviesUrl = `https://api.themoviedb.org/3/movie/popular?api_key=${process.env.API_KEY}&language=en-GB&page=1&region=GB`;
  // let topRatedMoviesUrl = `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.API_KEY}&language=en-GB&page=1&region=GB`;

  // const urls = [newReleasesUrl, popularMoviesUrl, topRatedMoviesUrl];

  // try {
  //   let data = await Promise.all(
  //     urls.map((url) => fetch(url).then((response) => response.json()))
  //   ).catch((error) => console.log(error));
  //   return {
  //     props: {
  //       newReleases: data[0].results,
  //       popularMovies: data[1].results,
  //       topRatedMovies: data[2].results,
  //     },
  //   };
  // } catch (error) {
  //   console.log(error);
  // }

  const data = await getMovies();

  return {
    props: {
      newReleases: data[0].results,
      popularMovies: data[1].results,
      topRatedMovies: data[2].results,
    },
  };
}
