import Head from "next/head";
import MovieCarousel from "../components/layout/MovieCarousel";
import { getMovies } from "../helpers/api-util";

export default function Home({ newReleases, popularMovies, topRatedMovies }) {
  // console.log(newReleases, popularMovies, topRatedMovies);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MovieCarousel movies={newReleases} title={"New Releases"} />
      <MovieCarousel movies={popularMovies} title={"Most Popular"} />
      <MovieCarousel movies={topRatedMovies} title={"Top Rated"} />
    </>
  );
}

export async function getStaticProps() {
  const data = await getMovies();

  return {
    props: {
      newReleases: data[0].results,
      popularMovies: data[1].results,
      topRatedMovies: data[2].results,
    },
  };
}
